services:
  couchdb:
    image: apache/couchdb:3
    container_name: couchdb-livesync
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    ports:
      - "127.0.0.1:5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
      # - ./config/local.ini:/opt/couchdb/etc/local.d/local.ini:ro

volumes:
  couchdb_data:

