services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../../.env
    volumes:
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - mariadb
      - zigbee2mqtt
      - eclipse-mosquitto
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mariadb:
    image: mariadb:11
    container_name: homeassistant-db
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      MARIADB_DATABASE: ha_db
      MARIADB_USER: homeassistant
      MARIADB_PASSWORD: ${HA_MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${HA_MYSQL_ROOT_PASSWORD}
    volumes:
      - ./store/mariadb:/var/lib/mysql
    # user: ${LOCAL_USER}

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  eclipse-mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../../.env
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/mosquitto/passwd:/mosquitto/config/passwd:ro
      - ./store/mosquitto/data:/mosquitto/data
      - ./store/mosquitto/log:/mosquitto/log
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../../.env
    environment:
      TZ: ${TZ}
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE_ADAPTER_TTY}:/dev/ttyZigbee
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    env_file:
      - ../../.env
    user: ${PUID}:${PGID}
    ports:
      - "127.0.0.1:${NODE_RED_PORT}:1880"
    environment:
      TZ: ${TZ}
      NODE_OPTIONS: --max-old-space-size=256
    volumes:
      - ./nodered:/data
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
