services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - ../.env  # Load environment variables from ../.env
    depends_on:
      - mariadb
      - zigbee2mqtt
      - eclipse-mosquitto

  # MariaDb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ../.env  # Load environment variables from ../.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
    user: "${LOCAL_USER}"
    volumes:
      - ./store/mariadb:/var/lib/mysql


  # eclipse-mosquitto (MQTT broker)
  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../.env  # Load environment variables from ../.env
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/mosquitto/passwd:/mosquitto/config/passwd

  # zigbee2mqtt
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../.env  # Load environment variables from ../.env
    environment:
      - TZ=${TZ}
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - "${ZIGBEE_ADAPTER_TTY}:/dev/ttyZigbee"

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    env_file: [ ../.env ]
    user: "${PUID}:${PGID}"
    network_mode: host
    environment:
      - TZ=${TZ}
      - PORT=${NODE_RED_PORT}
      - NODE_OPTIONS=--max-old-space-size=256
    volumes:
      - ./nodered:/data

