x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - "127.0.0.1:${HEIMDALL_PORT}:80"
    volumes:
      - ./heimdall/config:/config
    security_opt:
      - no-new-privileges:true
    logging: *default-logging

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file: ../.env
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
    ports:
      - "127.0.0.1:${VAULT_WARDEN_PORT}:80"
    volumes:
      - ./vaultwarden/data:/data
    security_opt:
      - no-new-privileges:true
    logging: *default-logging
