services:
  watchtower:
    image: nickfedor/watchtower
    hostname: watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=604800  # Set to 1 week (in seconds)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
    restart: unless-stopped


