# Alarm helpers & groups (single package file)

input_select:
  alarm_mode:
    name: Alarm Mode
    options: [disarmed, armed_home, armed_night]
    initial: disarmed

input_boolean:
  alarm_triggered:
    name: Alarm Triggered
    initial: false

input_number:
  alarm_siren_seconds:
    name: Siren Duration (sec)
    min: 3
    max: 900
    step: 1
    unit_of_measurement: s
    mode: slider
    initial: 60

group:
  doors_all:
    name: All Doors
    entities:
      - binary_sensor.main_door_ds_contact
      - binary_sensor.kitchen_balcony_ds_contact
      - binary_sensor.dinning_balcony_ds_contact

  motion_all:
    name: All Motion
    entities:
      - binary_sensor.ms_dining_occupancy
      - binary_sensor.ms_kitchen_occupancy
      - binary_sensor.ms_stairs_occupancy

  tamper_all:
    name: All Tamper
    entities:
      - binary_sensor.main_door_ds_tamper
      - binary_sensor.kitchen_balcony_ds_tamper
      - binary_sensor.dinning_balcony_ds_tamper
